const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;

export const defaultMeta = {
    siteName: "Muralidharan | Connect Training Solutions",
    author: "Muralidharan R",
    image: `${baseUrl}/photo.png`,
    keywords: [
        "Muralidharan Portfolio",
        "Connect Murali",
        "Muralidharan",
        "Trainer",
        "Corporate Trainer",
        "Corporate Trainer in India",
        "Global Corporate Training Solutions",
        "Leadership Development Trainer",
        "Soft Skills Training for Professionals",
        "Aptitude and Cognitive Skills Coaching",
        "Team Building Training for Corporates",
        "Career Guidance Coach for Students",
        "Faculty Development Programs",
        "Customer Service Training Expert",
        "Career Coach for Schools and Colleges",
        "Online Corporate Training Programs",
        "Corporate Workshops on Leadership",
        "International Corporate Trainer",
        "Training for Professional Development",
        "Executive Coaching and Leadership Skills",
        "Communication and Presentation Skills Training",
        "Personal Development and Soft Skills Coach",
        "Employee Skill Development",
        "Corporate Training Workshops",
        "Career Coaching for College Students",
        "Customer Service Skills Development",
        "Team Dynamics and Collaboration Workshops",
        "Leadership Training for Executives",
        "Professional Skills Development",
        "Soft Skills Training for Students",
        "Cognitive Development for Leaders",
        "Career Path Guidance for Professionals",
        "Aptitude Training for Career Success",
        "Global Leadership Training",
        "Corporate Skill Enhancement Programs",
        "Virtual Corporate Training Programs",
        "Cross-Cultural Communication Training",
        "Corporate Trainer in USA",
        "Leadership Training in the UK",
        "Soft Skills Trainer in Singapore",
        "Career Coach for Students in Australia",
        "Corporate Workshops in Middle East",
        "Team Building Training for Companies in Europe",
        "Professional Development Trainer in Asia",
        "Executive Leadership Training for Corporates",
        "Sales and Negotiation Skills Training",
        "Corporate Trainer for IT Professionals",
        "Management Skills Development for Leaders",
        "Advanced Presentation Skills for Executives",
        "HR and Talent Development Training",
        "Conflict Resolution and Team Building Workshops",
        "Employee Engagement and Productivity Coaching",
        "Time Management and Productivity Skills Training",
        "Motivational Speaker and Corporate Coach",
        "Organizational Change and Leadership Coaching",
        "Emotional Intelligence Training for Managers",
        "Global Training Programs for Remote Teams",
        "Corporate Trainer for Fortune 500 Companies",
        "Behavioral Skills Coaching for Executives",
        "Stress Management for Corporate Employees",
        "Professional Growth and Career Advancement Training",
        "Corporate Wellness and Employee Wellbeing Programs",
        "Conflict Management and Team Dynamics Coaching",
        "Public Speaking and Communication Mastery",
        "High-Performance Team Coaching",
        "Leadership Coaching for Startup Founders",
        "Corporate Etiquette and Professionalism Training",
        "Cross-Functional Team Collaboration Workshops",
        "Advanced Leadership Strategies for CEOs",
        "Business Communication Skills Development",
        "Virtual Team Leadership Coaching",
        "Corporate Training for Sales Teams"
    ],
    twitterCard: "summary_large_image",
    socialLinks: {
        linkedIn: "https://www.linkedin.com/in/muralidharan",
        twitter: "https://twitter.com/muralidharan",
        github: "https://github.com/muralidharan",
    },
    organization: {
        name: "Connect Training Solutions",
        url: baseUrl,
    },
    address: {
        locality: "Tirunelveli",
        region: "Tamil Nadu",
        postalCode: "627001",
        country: "India",
    },
};

export const meta = {
    landing: {
        title: "Muralidharan | Connect Training Solutions",
        description: "Personal portfolio website of Muralidharan showcasing skills, blogs, podcasts, and more.",
        url: `${baseUrl}/`,
        ...defaultMeta,
    },
    blogs: {
        title: "Blogs | Muralidharan",
        description: "Explore blogs by Muralidharan R on corporate training, soft skills, and personal development.",
        url: `${baseUrl}/blogs`,
        ...defaultMeta,
    },
    gallery: {
        title: "Gallery | Muralidharan",
        description: "Browse through Muralidharan's project galleries and corporate training visuals.",
        url: `${baseUrl}/gallery`,
        ...defaultMeta,
    },
    podcasts: {
        title: "Podcasts | Muralidharan",
        description: "Listen to Muralidharan's podcasts on corporate training, leadership, and skill development.",
        url: `${baseUrl}/podcasts`,
        ...defaultMeta,
    },
};
